version: '3'
services:
  energy-label:
    image: webapp-flask
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - ../../code:/app
    ports:
      - "8081:8080"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    networks:
      - energy

networks:
  energy:
    external: true