version: '3'
services:
  energy-label:
    image: webapp-flask
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - ../../code:/app
    # depends_on:
    #   - stock-db
    ports:
      - "8081:8080"
    environment:
    #   - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@stock-db/${DATABASE_NAME}
    #   - DATABASE_HOST=stock-db
      - FLASK_APP=./server.py
    networks:
      - energy
#   stock-db:
#     image: postgres:11
#     restart: always
#     environment:
#       POSTGRES_USER: artificial
#       POSTGRES_PASSWORD: artificial
#       POSTGRES_DB: artificial
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - artificial

volumes:
  pgdata:

networks:
  energy:
    external: true