version: '3'
services:
  energy-label:
    image: webapp-flask
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - ../../app:/app
    ports:
      - '8081:8080'
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - DB_API_KEY=${DB_API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER_ID=${USER_ID}
      - FIREBASE_type=${FIREBASE_type}
      - FIREBASE_project_id=${FIREBASE_project_id}
      - FIREBASE_private_key_id=${FIREBASE_private_key_id}
      - FIREBASE_private_key=${FIREBASE_private_key}
      - FIREBASE_client_email=${FIREBASE_client_email}
      - FIREBASE_client_id=${FIREBASE_client_id}
      - FIREBASE_auth_uri=${FIREBASE_auth_uri}
      - FIREBASE_token_uri=${FIREBASE_token_uri}
      - FIREBASE_auth_provider_x509_cert_url=${FIREBASE_auth_provider_x509_cert_url}
      - FIREBASE_client_x509_cert_url=${FIREBASE_client_x509_cert_url}

    networks:
      - energy

networks:
  energy:
    external: true
