FROM python:3.6

RUN pip install --upgrade pip

WORKDIR /src
RUN useradd -m worker
RUN chown worker:worker .
USER worker

# RUN pip install --upgrade --user pipenv
ENV PATH=/home/worker/.local/bin:$PATH

COPY --chown=worker:worker ./src /src

# RUN pipenv lock -r > requirements.txt
RUN python -m pip install -r requirements.txt
