version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      - ../../config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - energy

  energy-label:
    image: webapp-flask
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile.server
    command: ["python", "server.py"]
    volumes:
      - ../../src:/src
    ports:
      - '8081:8080'
    # depends_on:
    #   - redis
    networks:
      - energy
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - PORT=${PORT}
      - DB_API_KEY=${DB_API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - USER_ID=${USER_ID}
      - FIREBASE_type=${FIREBASE_type}
      - FIREBASE_project_id=${FIREBASE_project_id}
      - FIREBASE_private_key_id=${FIREBASE_private_key_id}
      - FIREBASE_private_key=${FIREBASE_private_key}
      - FIREBASE_client_email=${FIREBASE_client_email}
      - FIREBASE_client_id=${FIREBASE_client_id}
      - FIREBASE_auth_uri=${FIREBASE_auth_uri}
      - FIREBASE_token_uri=${FIREBASE_token_uri}
      - FIREBASE_auth_provider_x509_cert_url=${FIREBASE_auth_provider_x509_cert_url}
      - FIREBASE_client_x509_cert_url=${FIREBASE_client_x509_cert_url}
      - MONGO_URL=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority
      - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}

  worker:
    image: webapp-flask
    command: python worker.py
    volumes:
      - ../../src:/src
    # depends_on:
    #   - redis
    networks:
      - energy
    environment:
      - DB_API_KEY=${DB_API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - MONGO_URL=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority
      - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}

  redis-dashboard:
    image: eoranged/rq-dashboard:latest
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile.redis
    ports:
      - 9181:9181
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://${REDIS_USER}:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - RQ_DASHBOARD_USERNAME=${REDIS_USER}
      - RQ_DASHBOARD_PASSWORD=${REDIS_PASS}
    # depends_on:
    #   - redis
    networks:
      - energy

networks:
  energy:
    external: true
