version: '3'
services:
  energy-label:
    image: webapp-flask
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - ../../app:/app
    ports:
      - '8081:8080'
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - DB_API_KEY=${DB_API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
    networks:
      - energy

networks:
  energy:
    external: true
